---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "DivSeek Canada Pilot Project"
keywords:    "DivSeek, Canada, Divseek Canada, Tripal, Docker, Breeding, Crop"
description: "Scientific project to build a platform for accessing crop-focused data about Canadian plant genetic resources for crop improvement."
source_link: "https://github.com/DivSeek-Canada/divseek-canada.github.io"
favicon:     "img/favicon.png"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  red:       '#8e1a00'
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#00487F'
  green:     '#669C21'

kramdown:
  auto_ids:  false
